[tool.poetry]
name = "form_ever"
version = "0.1.0"
description = "Form Ever ğŸ“ is an AI-powered agent that simplifies the process of creating smart surveys. Effortlessly distribute them and get detailed analysis ğŸ“Š, giving you the insights you need. Whether for business, research, or general feedback collection, Form Ever makes survey management easy and efficient ğŸ¤–."
authors = ["stevieflyer"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
# autom = { git = "git@github.com:NaturaFlex/autom.git", branch = "main" }
autom = { path = "/home/steve/workspace/autom" }
google-api-python-client = "^2.146.0"
google-auth-httplib2 = "^0.2.0"
oauth2client = "^4.1.3"

[tool.autom]
qualifier = "form_ever"
name = "Form Ever"
owner_qualifier = "steveflyer"
owner_email = "steveflyer7@gmail.com"
description = "Form Ever ğŸ“ is an AI-powered agent that simplifies the process of creating smart surveys. Effortlessly distribute them and get detailed analysis ğŸ“Š, giving you the insights you need. Whether for business, research, or general feedback collection, Form Ever makes survey management easy and efficient ğŸ¤–."
python_version = "3.11"
python_version_spec = "^3.11"
publicity = "public"
github_repo_url = "https://github.com/stevieflyer/form_ever.git"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"